// Code generated by protoc-gen-sqlitex. DO NOT EDIT.
// source: testmodels.proto

package testmodels

import (
	"bytes"
	"encoding/binary"
	"fmt"
	zstd "github.com/klauspost/compress/zstd"
	"github.com/mogumc/sqlitex"
	"github.com/mogumc/sqlitex/internal/encoding"
	"strings"
	"sync"
	"time"
)

var (
	_zstdEnc *zstd.Encoder
	_zstdDec *zstd.Decoder
)

func init() {
	var err error
	_zstdEnc, err = zstd.NewWriter(nil, zstd.WithEncoderLevel(zstd.SpeedFastest))
	if err != nil {
		panic(err)
	}
	_zstdDec, err = zstd.NewReader(nil, zstd.WithDecoderConcurrency(0))
	if err != nil {
		panic(err)
	}
}

func _compressZstd(src []byte) []byte {
	return _zstdEnc.EncodeAll(src, nil)
}

func _decompressZstd(src []byte) ([]byte, error) {
	return _zstdDec.DecodeAll(src, nil)
}

func splitWhere(cond string) []string {
	lastSpace := -1
	for i := len(cond) - 1; i >= 0; i-- {
		if cond[i] == ' ' {
			lastSpace = i
			break
		}
	}
	if lastSpace < 0 {
		return nil
	}
	inner := cond[:lastSpace]
	for i := len(inner) - 1; i >= 0; i-- {
		if inner[i] == ' ' {
			return []string{inner[:i], inner[i+1:]}
		}
	}
	return nil
}

// Serialize 将 User 序列化为字节切片。
func (m *User) Serialize() []byte {
	size := m.Size()
	buf := make([]byte, size)
	off := 0
	binary.LittleEndian.PutUint64(buf[off:], uint64(m.Id))
	off += 8
	// Name (varlen): uint32 length prefix + data
	binary.LittleEndian.PutUint32(buf[off:], uint32(len(m.Name)))
	off += 4
	copy(buf[off:], m.Name)
	off += len(m.Name)
	// Email (varlen): uint32 length prefix + data
	binary.LittleEndian.PutUint32(buf[off:], uint32(len(m.Email)))
	off += 4
	copy(buf[off:], m.Email)
	off += len(m.Email)
	binary.LittleEndian.PutUint64(buf[off:], uint64(m.CreatedAt))
	off += 8
	// Active (fixed 1B)
	if m.Active {
		buf[off] = 1
	} else {
		buf[off] = 0
	}
	off += 1
	// Bio (compressible varlen): [uint32 dataLen][uint32 originalLen][data]
	raw := []byte(m.Bio)
	compressed := _compressZstd(raw)
	if len(compressed) < len(raw) {
		binary.LittleEndian.PutUint32(buf[off:], uint32(len(compressed)))
		off += 4
		binary.LittleEndian.PutUint32(buf[off:], uint32(len(raw)))
		off += 4
		copy(buf[off:], compressed)
		off += len(compressed)
	} else {
		binary.LittleEndian.PutUint32(buf[off:], uint32(len(raw)))
		off += 4
		binary.LittleEndian.PutUint32(buf[off:], uint32(len(raw)))
		off += 4
		copy(buf[off:], raw)
		off += len(raw)
	}
	return buf
}

// DeserializeUser 从字节切片反序列化为 User。
func DeserializeUser(data []byte) (*User, error) {
	if len(data) < 25 {
		return nil, fmt.Errorf("sqlitex: User data too short: %d < 25", len(data))
	}
	m := &User{}
	off := 0
	var vLen int
	if off+8 > len(data) {
		return nil, fmt.Errorf("sqlitex: User.Id truncated")
	}
	m.Id = int64(binary.LittleEndian.Uint64(data[off:]))
	off += 8
	// Name (varlen)
	if off+4 > len(data) {
		return nil, fmt.Errorf("sqlitex: User.Name length prefix truncated")
	}
	vLen = int(binary.LittleEndian.Uint32(data[off:]))
	off += 4
	if off+vLen > len(data) {
		return nil, fmt.Errorf("sqlitex: User.Name data truncated: need %d, have %d", vLen, len(data)-off)
	}
	m.Name = string(data[off : off+vLen])
	off += vLen
	// Email (varlen)
	if off+4 > len(data) {
		return nil, fmt.Errorf("sqlitex: User.Email length prefix truncated")
	}
	vLen = int(binary.LittleEndian.Uint32(data[off:]))
	off += 4
	if off+vLen > len(data) {
		return nil, fmt.Errorf("sqlitex: User.Email data truncated: need %d, have %d", vLen, len(data)-off)
	}
	m.Email = string(data[off : off+vLen])
	off += vLen
	if off+8 > len(data) {
		return nil, fmt.Errorf("sqlitex: User.CreatedAt truncated")
	}
	m.CreatedAt = int64(binary.LittleEndian.Uint64(data[off:]))
	off += 8
	if off+1 > len(data) {
		return nil, fmt.Errorf("sqlitex: User.Active truncated")
	}
	m.Active = data[off] != 0
	off += 1
	// Bio (compressible varlen)
	if off+8 > len(data) {
		return nil, fmt.Errorf("sqlitex: User.Bio truncated")
	}
	vLen = int(binary.LittleEndian.Uint32(data[off:]))
	origLen := int(binary.LittleEndian.Uint32(data[off+4:]))
	off += 8
	if off+vLen > len(data) {
		return nil, fmt.Errorf("sqlitex: User.Bio data truncated: need %d, have %d", vLen, len(data)-off)
	}
	if vLen == origLen {
		m.Bio = string(data[off : off+vLen])
	} else {
		dec, err := _decompressZstd(data[off : off+vLen])
		if err != nil {
			return nil, fmt.Errorf("sqlitex: User.Bio zstd decompress: %w", err)
		}
		m.Bio = string(dec)
	}
	off += vLen
	return m, nil
}

// Size 返回序列化所需的缓冲区大小（上限估计）。
func (m *User) Size() int {
	size := 25
	size += 4 + len(m.Name)
	size += 4 + len(m.Email)
	size += 4 + len(m.Bio)
	return size
}

// UserStore 是 User 的强类型存储接口。
// Create/Update 在唯一索引字段值冲突时返回错误，可用 errors.Is(err, sqlitex.ErrDuplicateKey) 匹配。
type UserStore interface {
	Create(m *User) error
	Update(m *User) error
	Delete(Id int64) error
	Get(Id int64) (*User, error)
}

// userStore 实现 UserStore 接口。
type userStore struct {
	db      *sqlitex.DB
	tableID uint64
}

// NewUserStore 创建 UserStore 实例。
func NewUserStore(db *sqlitex.DB) UserStore {
	return &userStore{db: db, tableID: 1}
}

// Create 创建新的 User 记录（主键已存在时为覆盖语义）。
// 通过 WriteBatch 原子写入主数据行 + 所有二级索引。
// 唯一索引冲突时返回 errors.Is 可匹配的 sqlitex.ErrDuplicateKey，且不发生任何落盘。
func (s *userStore) Create(m *User) error {
	if m == nil {
		return fmt.Errorf("sqlitex: cannot create nil User")
	}

	pkBytes := encodeUserPrimaryKey(m.Id)
	dataKey := encoding.EncodeKey(s.tableID, pkBytes)
	value := m.Serialize()

	ops := make([]sqlitex.KVPair, 0, 1+2*2)
	ops = append(ops, sqlitex.KVPair{Key: dataKey, Value: value})

	// 覆盖创建：读取旧值并清理旧索引条目，防止旧唯一索引条目残留
	// 导致其他记录的同值写入被误拒。
	old, _ := s.Get(m.Id)
	if old != nil {
		ops = append(ops, sqlitex.KVPair{
			Key:    encoding.EncodeUniqueIndexKey(s.tableID, 3, encodeUserIndexEmailValue(old.Email)),
			Delete: true,
		})
		ops = append(ops, sqlitex.KVPair{
			Key:    encoding.EncodeIndexKey(s.tableID, 4, encodeUserIndexCreatedAtValue(old.CreatedAt), pkBytes),
			Delete: true,
		})
	}
	// 唯一索引 email 冲突检查：唯一条目的 Value 为持有者 PK，
	// 等于本记录 PK 视为覆盖自身，放行。检查与提交之间为 check-then-write，
	// 极端并发窗口下可能双双通过（后写者覆盖唯一条目），见 docs/schema.md。
	ukeyEmail := encoding.EncodeUniqueIndexKey(s.tableID, 3, encodeUserIndexEmailValue(m.Email))
	if existing, err := s.db.Get(ukeyEmail); err != nil {
		return fmt.Errorf("sqlitex: check unique index User.email: %w", err)
	} else if existing != nil && !bytes.Equal(existing, pkBytes) {
		return fmt.Errorf("sqlitex: create User: unique index User.email conflict: %w", sqlitex.ErrDuplicateKey)
	}
	ops = append(ops, sqlitex.KVPair{Key: ukeyEmail, Value: pkBytes})
	ops = append(ops, sqlitex.KVPair{
		Key:   encoding.EncodeIndexKey(s.tableID, 4, encodeUserIndexCreatedAtValue(m.CreatedAt), pkBytes),
		Value: pkBytes,
	})
	return s.db.WriteBatch(ops)
}

// Update 更新已存在的 User 记录。
// 先 Get 旧值删除旧索引，再原子写入新数据+新索引。
// 唯一索引字段值与既有记录冲突时返回 sqlitex.ErrDuplicateKey（自身持有则放行），
// 此时 WriteBatch 未提交，不发生任何落盘。
func (s *userStore) Update(m *User) error {
	if m == nil {
		return fmt.Errorf("sqlitex: cannot update nil User")
	}

	pkBytes := encodeUserPrimaryKey(m.Id)
	dataKey := encoding.EncodeKey(s.tableID, pkBytes)
	value := m.Serialize()
	ops := make([]sqlitex.KVPair, 0, 1+2*2)
	ops = append(ops, sqlitex.KVPair{Key: dataKey, Value: value})

	// 获取旧值，删除旧索引条目
	old, _ := s.Get(m.Id)
	if old != nil {
		ops = append(ops, sqlitex.KVPair{
			Key:    encoding.EncodeUniqueIndexKey(s.tableID, 3, encodeUserIndexEmailValue(old.Email)),
			Delete: true,
		})
		ops = append(ops, sqlitex.KVPair{
			Key:    encoding.EncodeIndexKey(s.tableID, 4, encodeUserIndexCreatedAtValue(old.CreatedAt), pkBytes),
			Delete: true,
		})
	}
	// 唯一索引 email 冲突检查：唯一条目的 Value 为持有者 PK，
	// 等于本记录 PK 视为值未变更（自身持有），放行。
	ukeyEmail := encoding.EncodeUniqueIndexKey(s.tableID, 3, encodeUserIndexEmailValue(m.Email))
	if existing, err := s.db.Get(ukeyEmail); err != nil {
		return fmt.Errorf("sqlitex: check unique index User.email: %w", err)
	} else if existing != nil && !bytes.Equal(existing, pkBytes) {
		return fmt.Errorf("sqlitex: update User: unique index User.email conflict: %w", sqlitex.ErrDuplicateKey)
	}
	ops = append(ops, sqlitex.KVPair{
		Key:   encoding.EncodeUniqueIndexKey(s.tableID, 3, encodeUserIndexEmailValue(m.Email)),
		Value: pkBytes,
	})
	ops = append(ops, sqlitex.KVPair{
		Key:   encoding.EncodeIndexKey(s.tableID, 4, encodeUserIndexCreatedAtValue(m.CreatedAt), pkBytes),
		Value: pkBytes,
	})
	return s.db.WriteBatch(ops)
}

// Delete 删除指定主键的 User 记录及其所有索引。
// 先 Get 获取旧值以构造正确的索引 Key，再原子删除。
func (s *userStore) Delete(Id int64) error {
	pkBytes := encodeUserPrimaryKey(Id)
	dataKey := encoding.EncodeKey(s.tableID, pkBytes)

	ops := make([]sqlitex.KVPair, 0, 1+2)
	ops = append(ops, sqlitex.KVPair{Key: dataKey, Delete: true})

	// 获取旧值以确定要删除的索引 Key
	old, _ := s.Get(Id)
	if old != nil {
		ops = append(ops, sqlitex.KVPair{
			Key:    encoding.EncodeUniqueIndexKey(s.tableID, 3, encodeUserIndexEmailValue(old.Email)),
			Delete: true,
		})
		ops = append(ops, sqlitex.KVPair{
			Key:    encoding.EncodeIndexKey(s.tableID, 4, encodeUserIndexCreatedAtValue(old.CreatedAt), pkBytes),
			Delete: true,
		})
	}
	return s.db.WriteBatch(ops)
}

// Get 根据主键查询 User 记录。
func (s *userStore) Get(Id int64) (*User, error) {
	pkBytes := encodeUserPrimaryKey(Id)
	key := encoding.EncodeKey(s.tableID, pkBytes)

	value, err := s.db.Get(key)
	if err != nil {
		return nil, fmt.Errorf("sqlitex: get User: %w", err)
	}
	if value == nil {
		return nil, nil
	}
	return DeserializeUser(value)
}

// encodeUserPrimaryKey 编码主键为字节切片。
func encodeUserPrimaryKey(Id int64) []byte {
	buf := make([]byte, 8)
	binary.LittleEndian.PutUint64(buf, uint64(Id))
	return buf
}
func encodeUserIndexEmailValue(v string) []byte { return []byte(v) }
func encodeUserIndexCreatedAtValue(v int64) []byte {
	buf := make([]byte, 8)
	binary.LittleEndian.PutUint64(buf, uint64(v))
	return buf
}

type UserQuery struct {
	db      *sqlitex.DB
	where   []string
	args    []interface{}
	limit   int
	lastKey []byte
}

func NewUserQuery(db *sqlitex.DB) *UserQuery {
	return &UserQuery{db: db, where: make([]string, 0), args: make([]interface{}, 0)}
}

func (q *UserQuery) WhereName(op string, value string) *UserQuery {
	q.where = append(q.where, "Name "+op+" ?")
	q.args = append(q.args, value)
	return q
}

func (q *UserQuery) WhereEmail(op string, value string) *UserQuery {
	q.where = append(q.where, "Email "+op+" ?")
	q.args = append(q.args, value)
	return q
}

func (q *UserQuery) WhereCreatedAt(op string, value int64) *UserQuery {
	q.where = append(q.where, "CreatedAt "+op+" ?")
	q.args = append(q.args, value)
	return q
}

func (q *UserQuery) WhereActive(op string, value bool) *UserQuery {
	q.where = append(q.where, "Active "+op+" ?")
	q.args = append(q.args, value)
	return q
}

func (q *UserQuery) WhereBio(op string, value string) *UserQuery {
	q.where = append(q.where, "Bio "+op+" ?")
	q.args = append(q.args, value)
	return q
}

func (q *UserQuery) Limit(n int) *UserQuery             { q.limit = n; return q }
func (q *UserQuery) AfterKey(lastKey []byte) *UserQuery { q.lastKey = lastKey; return q }
func (q *UserQuery) Exec() ([]*User, error) {
	if len(q.where) > 0 {
		parts := splitWhere(q.where[0])
		if len(parts) == 2 && parts[0] == "Email" && parts[1] == "=" {
			return q.execIndexed()
		}
	}
	return q.execFullScan()
}

func (q *UserQuery) execIndexed() ([]*User, error) {
	val := q.args[0]
	var fieldValue []byte
	fieldValue = []byte(val.(string))
	prefix := encoding.EncodeIndexPrefix(1, 3, fieldValue)
	iter := q.db.Iterate(prefix)
	if iter == nil {
		return nil, nil
	}
	defer iter.Close()
	if len(q.lastKey) > 0 {
		iter.SeekLT(q.lastKey)
		if iter.Valid() {
			iter.Next()
		}
	}

	var results []*User
	for iter.Next() {
		pkBytes := iter.Value()
		dataKey := encoding.EncodeKey(1, pkBytes)
		value, err := q.db.Get(dataKey)
		if err != nil || value == nil {
			continue
		}
		m, err := DeserializeUser(value)
		if err != nil {
			continue
		}
		if len(q.where) > 1 && !q.matchWhereTail(m) {
			continue
		}
		results = append(results, m)
		if q.limit > 0 && len(results) >= q.limit {
			break
		}
	}
	return results, nil
}

func (q *UserQuery) execFullScan() ([]*User, error) {
	prefix := encoding.EncodeKey(1, nil)
	iter := q.db.Iterate(prefix)
	if iter == nil {
		return nil, nil
	}
	defer iter.Close()
	if len(q.lastKey) > 0 {
		iter.SeekLT(q.lastKey)
		if iter.Valid() {
			iter.Next()
		}
	}

	var results []*User
	for iter.Next() {
		value := iter.Value()
		m, err := DeserializeUser(value)
		if err != nil {
			continue
		}
		if q.matchWhere(m) {
			results = append(results, m)
			if q.limit > 0 && len(results) >= q.limit {
				break
			}
		}
	}
	return results, nil
}

func (q *UserQuery) First() (*User, error) {
	q.limit = 1
	r, e := q.Exec()
	if e != nil {
		return nil, e
	}
	if len(r) == 0 {
		return nil, nil
	}
	return r[0], nil
}
func (q *UserQuery) Count() (int, error) {
	r, e := q.Exec()
	if e != nil {
		return 0, e
	}
	return len(r), nil
}

func (q *UserQuery) matchWhere(item *User) bool {
	for _, cond := range q.where {
		parts := splitWhere(cond)
		if len(parts) != 2 {
			continue
		}
		field, op := parts[0], parts[1]
		switch field {
		case "Name":
			if !q.compareName(item.Name, op) {
				return false
			}
		case "Email":
			if !q.compareEmail(item.Email, op) {
				return false
			}
		case "CreatedAt":
			if !q.compareCreatedAt(item.CreatedAt, op) {
				return false
			}
		case "Active":
			if !q.compareActive(item.Active, op) {
				return false
			}
		case "Bio":
			if !q.compareBio(item.Bio, op) {
				return false
			}

		}
	}
	return true
}

func (q *UserQuery) matchWhereTail(item *User) bool {
	for i, cond := range q.where {
		if i == 0 {
			continue
		}
		parts := splitWhere(cond)
		if len(parts) != 2 {
			continue
		}
		field, op := parts[0], parts[1]
		switch field {
		case "Name":
			if !q.compareName(item.Name, op) {
				return false
			}
		case "Email":
			if !q.compareEmail(item.Email, op) {
				return false
			}
		case "CreatedAt":
			if !q.compareCreatedAt(item.CreatedAt, op) {
				return false
			}
		case "Active":
			if !q.compareActive(item.Active, op) {
				return false
			}
		case "Bio":
			if !q.compareBio(item.Bio, op) {
				return false
			}

		}
	}
	return true
}

func (q *UserQuery) compareName(actual string, op string) bool {
	targetIdx := -1

	for i, w := range q.where {
		parts := splitWhere(w)
		if len(parts) == 2 && parts[0] == "Name" && parts[1] == op {
			targetIdx = i
			break
		}
	}
	if targetIdx < 0 || targetIdx >= len(q.args) {
		return false
	}
	expected := q.args[targetIdx].(string)
	switch op {
	case "=":
		return actual == expected
	case "!=":
		return actual != expected
	case "LIKE":
		return strings.Contains(actual, expected)
	}
	return false
}

func (q *UserQuery) compareEmail(actual string, op string) bool {
	targetIdx := -1

	for i, w := range q.where {
		parts := splitWhere(w)
		if len(parts) == 2 && parts[0] == "Email" && parts[1] == op {
			targetIdx = i
			break
		}
	}
	if targetIdx < 0 || targetIdx >= len(q.args) {
		return false
	}
	expected := q.args[targetIdx].(string)
	switch op {
	case "=":
		return actual == expected
	case "!=":
		return actual != expected
	case "LIKE":
		return strings.Contains(actual, expected)
	}
	return false
}

func (q *UserQuery) compareCreatedAt(actual int64, op string) bool {
	targetIdx := -1

	for i, w := range q.where {
		parts := splitWhere(w)
		if len(parts) == 2 && parts[0] == "CreatedAt" && parts[1] == op {
			targetIdx = i
			break
		}
	}
	if targetIdx < 0 || targetIdx >= len(q.args) {
		return false
	}
	expected := q.args[targetIdx].(int64)
	switch op {
	case "=":
		return actual == expected
	case "!=":
		return actual != expected
	case ">":
		return actual > expected
	case "<":
		return actual < expected
	case ">=":
		return actual >= expected
	case "<=":
		return actual <= expected
	}
	return false
}

func (q *UserQuery) compareActive(actual bool, op string) bool {
	targetIdx := -1

	for i, w := range q.where {
		parts := splitWhere(w)
		if len(parts) == 2 && parts[0] == "Active" && parts[1] == op {
			targetIdx = i
			break
		}
	}
	if targetIdx < 0 || targetIdx >= len(q.args) {
		return false
	}
	expected := q.args[targetIdx].(bool)
	switch op {
	case "=":
		return actual == expected
	case "!=":
		return actual != expected
	}
	return false
}

func (q *UserQuery) compareBio(actual string, op string) bool {
	targetIdx := -1

	for i, w := range q.where {
		parts := splitWhere(w)
		if len(parts) == 2 && parts[0] == "Bio" && parts[1] == op {
			targetIdx = i
			break
		}
	}
	if targetIdx < 0 || targetIdx >= len(q.args) {
		return false
	}
	expected := q.args[targetIdx].(string)
	switch op {
	case "=":
		return actual == expected
	case "!=":
		return actual != expected
	case "LIKE":
		return strings.Contains(actual, expected)
	}
	return false
}

// mockUserStore 实现 UserStore 接口的内存版本，用于单元测试。
type mockUserStore struct {
	mu   sync.RWMutex
	data map[int64]*User
}

// NewMockUserStore 创建 Mock Store 实例。
func NewMockUserStore() *mockUserStore {
	return &mockUserStore{
		data: make(map[int64]*User),
	}
}

// cloneUser 逐字段拷贝记录，bytes/slice 深拷贝保证数据隔离。
// 不整体复制 struct：protoimpl.MessageState 含锁，整体赋值会触发 vet copies lock。
func cloneUser(src *User) *User {
	if src == nil {
		return nil
	}
	dst := &User{}
	dst.Id = src.Id
	dst.Name = src.Name
	dst.Email = src.Email
	dst.CreatedAt = src.CreatedAt
	dst.Active = src.Active
	dst.Bio = src.Bio
	return dst
}

// Create 创建记录。
func (m *mockUserStore) Create(record *User) error {
	if record == nil {
		return fmt.Errorf("sqlitex: cannot create nil User")
	}
	m.mu.Lock()
	defer m.mu.Unlock()
	if _, exists := m.data[record.Id]; exists {
		return fmt.Errorf("sqlitex: User with Id=%v already exists", record.Id)
	}
	// 深拷贝避免外部修改
	m.data[record.Id] = cloneUser(record)
	return nil
}

// Update 更新记录。
func (m *mockUserStore) Update(record *User) error {
	if record == nil {
		return fmt.Errorf("sqlitex: cannot update nil User")
	}
	m.mu.Lock()
	defer m.mu.Unlock()
	if _, exists := m.data[record.Id]; !exists {
		return fmt.Errorf("sqlitex: User with Id=%v not found", record.Id)
	}
	m.data[record.Id] = cloneUser(record)
	return nil
}

// Delete 删除记录。
func (m *mockUserStore) Delete(Id int64) error {
	m.mu.Lock()
	defer m.mu.Unlock()
	delete(m.data, Id)
	return nil
}

// Get 按主键查询。
func (m *mockUserStore) Get(Id int64) (*User, error) {
	m.mu.RLock()
	defer m.mu.RUnlock()
	record, exists := m.data[Id]
	if !exists {
		return nil, nil
	}
	return cloneUser(record), nil
}

// Serialize 将 Session 序列化为字节切片（无 TTL，永不过期）。
// 兼容外观：内部走 Meta Header 格式，expiresAt=0 表示永不过期。
func (m *Session) Serialize() []byte {
	return m.SerializeWithExpiry(0)
}

// SerializeWithExpiry 将 Session 序列化，Meta Header 记录过期时间戳。
// expiresAt 为 UnixNano，0 表示永不过期。
// Value 布局: [8B expiresAt][payload]
func (m *Session) SerializeWithExpiry(expiresAt int64) []byte {
	size := m.Size()
	buf := make([]byte, size)
	binary.LittleEndian.PutUint64(buf, uint64(expiresAt))
	off := 8
	binary.LittleEndian.PutUint64(buf[off:], uint64(m.Id))
	off += 8
	// Token (varlen): uint32 length prefix + data
	binary.LittleEndian.PutUint32(buf[off:], uint32(len(m.Token)))
	off += 4
	copy(buf[off:], m.Token)
	off += len(m.Token)
	// UserId (varlen): uint32 length prefix + data
	binary.LittleEndian.PutUint32(buf[off:], uint32(len(m.UserId)))
	off += 4
	copy(buf[off:], m.UserId)
	off += len(m.UserId)
	// Active (fixed 1B)
	if m.Active {
		buf[off] = 1
	} else {
		buf[off] = 0
	}
	off += 1
	return buf
}

// DeserializeSession 从字节切片反序列化为 Session。
// 忽略 Meta Header 的过期时间戳，返回数据本身。
func DeserializeSession(data []byte) (*Session, error) {
	m, _, err := DeserializeSessionMeta(data)
	return m, err
}

// DeserializeSessionMeta 反序列化并返回 Meta Header 中的过期时间戳。
// 返回的 expiresAt 为 UnixNano，0 表示永不过期。
func DeserializeSessionMeta(data []byte) (*Session, int64, error) {
	if len(data) < 9+8 {
		return nil, 0, fmt.Errorf("sqlitex: Session data too short: %d < 9+8", len(data))
	}
	expiresAt := int64(binary.LittleEndian.Uint64(data))
	m := &Session{}
	off := 8
	var vLen int
	if off+8 > len(data) {
		return nil, 0, fmt.Errorf("sqlitex: Session.Id truncated")
	}
	m.Id = int64(binary.LittleEndian.Uint64(data[off:]))
	off += 8
	// Token (varlen)
	if off+4 > len(data) {
		return nil, 0, fmt.Errorf("sqlitex: Session.Token length prefix truncated")
	}
	vLen = int(binary.LittleEndian.Uint32(data[off:]))
	off += 4
	if off+vLen > len(data) {
		return nil, 0, fmt.Errorf("sqlitex: Session.Token data truncated: need %d, have %d", vLen, len(data)-off)
	}
	m.Token = string(data[off : off+vLen])
	off += vLen
	// UserId (varlen)
	if off+4 > len(data) {
		return nil, 0, fmt.Errorf("sqlitex: Session.UserId length prefix truncated")
	}
	vLen = int(binary.LittleEndian.Uint32(data[off:]))
	off += 4
	if off+vLen > len(data) {
		return nil, 0, fmt.Errorf("sqlitex: Session.UserId data truncated: need %d, have %d", vLen, len(data)-off)
	}
	m.UserId = string(data[off : off+vLen])
	off += vLen
	if off+1 > len(data) {
		return nil, 0, fmt.Errorf("sqlitex: Session.Active truncated")
	}
	m.Active = data[off] != 0
	off += 1
	return m, expiresAt, nil
}

// Size 返回序列化所需的缓冲区大小（上限估计），含 8B Meta Header。
func (m *Session) Size() int {
	size := 9 + 8
	size += 4 + len(m.Token)
	size += 4 + len(m.UserId)
	return size
}

// SessionStore 是 Session 的强类型存储接口。
type SessionStore interface {
	Create(m *Session) error
	Update(m *Session) error
	Delete(Id int64) error
	Get(Id int64) (*Session, error)
	// PurgeExpired 主动清理所有过期记录（含索引），返回删除条数。
	// 供用户后台定时调用，消除惰性删除窗口期的逻辑过期数据。
	PurgeExpired() (int, error)
}

// sessionStore 实现 SessionStore 接口。
type sessionStore struct {
	db      *sqlitex.DB
	tableID uint64
}

// NewSessionStore 创建 SessionStore 实例。
func NewSessionStore(db *sqlitex.DB) SessionStore {
	return &sessionStore{db: db, tableID: 2}
}

// Create 创建新的 Session 记录（主键已存在时为覆盖语义）。
// 通过 WriteBatch 原子写入主数据行 + 所有二级索引。
// 记录级 TTL: 写入时计算 expiresAt = now + 1000000000ns，过期后惰性删除。
func (s *sessionStore) Create(m *Session) error {
	if m == nil {
		return fmt.Errorf("sqlitex: cannot create nil Session")
	}

	pkBytes := encodeSessionPrimaryKey(m.Id)
	dataKey := encoding.EncodeKey(s.tableID, pkBytes)
	value := m.SerializeWithExpiry(time.Now().UnixNano() + 1000000000)

	ops := make([]sqlitex.KVPair, 0, 1+2*1)
	ops = append(ops, sqlitex.KVPair{Key: dataKey, Value: value})

	// 覆盖创建：读取旧值并清理旧索引条目，防止旧唯一索引条目残留
	// 导致其他记录的同值写入被误拒。
	old, _ := s.Get(m.Id)
	if old != nil {
		ops = append(ops, sqlitex.KVPair{
			Key:    encoding.EncodeIndexKey(s.tableID, 3, encodeSessionIndexUserIdValue(old.UserId), pkBytes),
			Delete: true,
		})
	}
	ops = append(ops, sqlitex.KVPair{
		Key:   encoding.EncodeIndexKey(s.tableID, 3, encodeSessionIndexUserIdValue(m.UserId), pkBytes),
		Value: pkBytes,
	})
	return s.db.WriteBatch(ops)
}

// Update 更新已存在的 Session 记录。
// 先 Get 旧值删除旧索引，再原子写入新数据+新索引。
func (s *sessionStore) Update(m *Session) error {
	if m == nil {
		return fmt.Errorf("sqlitex: cannot update nil Session")
	}

	pkBytes := encodeSessionPrimaryKey(m.Id)
	dataKey := encoding.EncodeKey(s.tableID, pkBytes)
	value := m.SerializeWithExpiry(time.Now().UnixNano() + 1000000000)
	ops := make([]sqlitex.KVPair, 0, 1+2*1)
	ops = append(ops, sqlitex.KVPair{Key: dataKey, Value: value})

	// 获取旧值，删除旧索引条目
	old, _ := s.Get(m.Id)
	if old != nil {
		ops = append(ops, sqlitex.KVPair{
			Key:    encoding.EncodeIndexKey(s.tableID, 3, encodeSessionIndexUserIdValue(old.UserId), pkBytes),
			Delete: true,
		})
	}
	ops = append(ops, sqlitex.KVPair{
		Key:   encoding.EncodeIndexKey(s.tableID, 3, encodeSessionIndexUserIdValue(m.UserId), pkBytes),
		Value: pkBytes,
	})
	return s.db.WriteBatch(ops)
}

// Delete 删除指定主键的 Session 记录及其所有索引。
// 先 Get 获取旧值以构造正确的索引 Key，再原子删除。
func (s *sessionStore) Delete(Id int64) error {
	pkBytes := encodeSessionPrimaryKey(Id)
	dataKey := encoding.EncodeKey(s.tableID, pkBytes)

	ops := make([]sqlitex.KVPair, 0, 1+1)
	ops = append(ops, sqlitex.KVPair{Key: dataKey, Delete: true})

	// 获取旧值以确定要删除的索引 Key
	old, _ := s.Get(Id)
	if old != nil {
		ops = append(ops, sqlitex.KVPair{
			Key:    encoding.EncodeIndexKey(s.tableID, 3, encodeSessionIndexUserIdValue(old.UserId), pkBytes),
			Delete: true,
		})
	}
	return s.db.WriteBatch(ops)
}

// Get 根据主键查询 Session 记录。
// TTL 惰性删除: 记录已过期时物理删除并返回 nil。
func (s *sessionStore) Get(Id int64) (*Session, error) {
	pkBytes := encodeSessionPrimaryKey(Id)
	key := encoding.EncodeKey(s.tableID, pkBytes)

	value, err := s.db.Get(key)
	if err != nil {
		return nil, fmt.Errorf("sqlitex: get Session: %w", err)
	}
	if value == nil {
		return nil, nil
	}
	// 惰性删除: 检查 Meta Header 过期时间戳
	m, expiresAt, err := DeserializeSessionMeta(value)
	if err != nil {
		return nil, err
	}
	if expiresAt > 0 && time.Now().UnixNano() > expiresAt {
		// 过期: 原子删除数据行 + 索引行（产生 tombstone，Compaction 时物理回收）
		deleteSessionWithIndexes(s.db, s.tableID, key, m)
		return nil, nil
	}
	return m, nil
}

// encodeSessionPrimaryKey 编码主键为字节切片。
func encodeSessionPrimaryKey(Id int64) []byte {
	buf := make([]byte, 8)
	binary.LittleEndian.PutUint64(buf, uint64(Id))
	return buf
}
func encodeSessionIndexUserIdValue(v string) []byte { return []byte(v) }

// deleteSessionWithIndexes 原子删除记录及其全部索引条目。
// 供 TTL 惰性删除与 PurgeExpired 复用，保证数据行与索引行一致清理。
func deleteSessionWithIndexes(db *sqlitex.DB, tableID uint64, dataKey []byte, m *Session) error {
	_, pkBytes, err := encoding.DecodeKey(dataKey)
	if err != nil {
		return err
	}
	ops := make([]sqlitex.KVPair, 0, 1+1)
	ops = append(ops, sqlitex.KVPair{Key: dataKey, Delete: true})
	ops = append(ops, sqlitex.KVPair{
		Key:    encoding.EncodeIndexKey(tableID, 3, encodeSessionIndexUserIdValue(m.UserId), pkBytes),
		Delete: true,
	})
	return db.WriteBatch(ops)
}

// PurgeExpired 主动清理全部过期记录及其索引，返回删除条数。
// 调用时机由用户决定（如后台定时任务），用于消除惰性删除窗口期的逻辑过期数据，
// 同时提前释放墓碑空间，降低 Compaction 压力。
func (s *sessionStore) PurgeExpired() (int, error) {
	prefix := encoding.EncodeKey(s.tableID, nil)
	iter := s.db.Iterate(prefix)
	if iter == nil {
		return 0, nil
	}
	defer iter.Close()

	count := 0
	now := time.Now().UnixNano()
	for iter.Next() {
		key := iter.Key()
		m, expiresAt, err := DeserializeSessionMeta(iter.Value())
		if err != nil {
			continue // 跳过损坏数据
		}
		if expiresAt > 0 && now > expiresAt {
			if err := deleteSessionWithIndexes(s.db, s.tableID, key, m); err == nil {
				count++
			}
		}
	}
	return count, nil
}

type SessionQuery struct {
	db      *sqlitex.DB
	where   []string
	args    []interface{}
	limit   int
	lastKey []byte
}

func NewSessionQuery(db *sqlitex.DB) *SessionQuery {
	return &SessionQuery{db: db, where: make([]string, 0), args: make([]interface{}, 0)}
}

func (q *SessionQuery) WhereToken(op string, value string) *SessionQuery {
	q.where = append(q.where, "Token "+op+" ?")
	q.args = append(q.args, value)
	return q
}

func (q *SessionQuery) WhereUserId(op string, value string) *SessionQuery {
	q.where = append(q.where, "UserId "+op+" ?")
	q.args = append(q.args, value)
	return q
}

func (q *SessionQuery) WhereActive(op string, value bool) *SessionQuery {
	q.where = append(q.where, "Active "+op+" ?")
	q.args = append(q.args, value)
	return q
}

func (q *SessionQuery) Limit(n int) *SessionQuery             { q.limit = n; return q }
func (q *SessionQuery) AfterKey(lastKey []byte) *SessionQuery { q.lastKey = lastKey; return q }
func (q *SessionQuery) Exec() ([]*Session, error) {
	if len(q.where) > 0 {
		parts := splitWhere(q.where[0])
		if len(parts) == 2 && parts[0] == "UserId" && parts[1] == "=" {
			return q.execIndexed()
		}
	}
	return q.execFullScan()
}

func (q *SessionQuery) execIndexed() ([]*Session, error) {
	val := q.args[0]
	var fieldValue []byte
	fieldValue = []byte(val.(string))
	prefix := encoding.EncodeIndexPrefix(2, 3, fieldValue)
	iter := q.db.Iterate(prefix)
	if iter == nil {
		return nil, nil
	}
	defer iter.Close()
	if len(q.lastKey) > 0 {
		iter.SeekLT(q.lastKey)
		if iter.Valid() {
			iter.Next()
		}
	}

	var results []*Session
	for iter.Next() {
		pkBytes := iter.Value()
		dataKey := encoding.EncodeKey(2, pkBytes)
		value, err := q.db.Get(dataKey)
		if err != nil || value == nil {
			continue
		}
		m, expiresAt, err := DeserializeSessionMeta(value)
		if err != nil {
			continue
		}
		if expiresAt > 0 && time.Now().UnixNano() > expiresAt {
			deleteSessionWithIndexes(q.db, 2, dataKey, m) // 惰性删除 + 索引清理
			continue
		}
		if len(q.where) > 1 && !q.matchWhereTail(m) {
			continue
		}
		results = append(results, m)
		if q.limit > 0 && len(results) >= q.limit {
			break
		}
	}
	return results, nil
}

func (q *SessionQuery) execFullScan() ([]*Session, error) {
	prefix := encoding.EncodeKey(2, nil)
	iter := q.db.Iterate(prefix)
	if iter == nil {
		return nil, nil
	}
	defer iter.Close()
	if len(q.lastKey) > 0 {
		iter.SeekLT(q.lastKey)
		if iter.Valid() {
			iter.Next()
		}
	}

	var results []*Session
	for iter.Next() {
		key := iter.Key()
		value := iter.Value()
		m, expiresAt, err := DeserializeSessionMeta(value)
		if err != nil {
			continue
		}
		if expiresAt > 0 && time.Now().UnixNano() > expiresAt {
			deleteSessionWithIndexes(q.db, 2, key, m) // 惰性删除 + 索引清理
			continue
		}
		if q.matchWhere(m) {
			results = append(results, m)
			if q.limit > 0 && len(results) >= q.limit {
				break
			}
		}
	}
	return results, nil
}

func (q *SessionQuery) First() (*Session, error) {
	q.limit = 1
	r, e := q.Exec()
	if e != nil {
		return nil, e
	}
	if len(r) == 0 {
		return nil, nil
	}
	return r[0], nil
}
func (q *SessionQuery) Count() (int, error) {
	r, e := q.Exec()
	if e != nil {
		return 0, e
	}
	return len(r), nil
}

func (q *SessionQuery) matchWhere(item *Session) bool {
	for _, cond := range q.where {
		parts := splitWhere(cond)
		if len(parts) != 2 {
			continue
		}
		field, op := parts[0], parts[1]
		switch field {
		case "Token":
			if !q.compareToken(item.Token, op) {
				return false
			}
		case "UserId":
			if !q.compareUserId(item.UserId, op) {
				return false
			}
		case "Active":
			if !q.compareActive(item.Active, op) {
				return false
			}

		}
	}
	return true
}

func (q *SessionQuery) matchWhereTail(item *Session) bool {
	for i, cond := range q.where {
		if i == 0 {
			continue
		}
		parts := splitWhere(cond)
		if len(parts) != 2 {
			continue
		}
		field, op := parts[0], parts[1]
		switch field {
		case "Token":
			if !q.compareToken(item.Token, op) {
				return false
			}
		case "UserId":
			if !q.compareUserId(item.UserId, op) {
				return false
			}
		case "Active":
			if !q.compareActive(item.Active, op) {
				return false
			}

		}
	}
	return true
}

func (q *SessionQuery) compareToken(actual string, op string) bool {
	targetIdx := -1

	for i, w := range q.where {
		parts := splitWhere(w)
		if len(parts) == 2 && parts[0] == "Token" && parts[1] == op {
			targetIdx = i
			break
		}
	}
	if targetIdx < 0 || targetIdx >= len(q.args) {
		return false
	}
	expected := q.args[targetIdx].(string)
	switch op {
	case "=":
		return actual == expected
	case "!=":
		return actual != expected
	case "LIKE":
		return strings.Contains(actual, expected)
	}
	return false
}

func (q *SessionQuery) compareUserId(actual string, op string) bool {
	targetIdx := -1

	for i, w := range q.where {
		parts := splitWhere(w)
		if len(parts) == 2 && parts[0] == "UserId" && parts[1] == op {
			targetIdx = i
			break
		}
	}
	if targetIdx < 0 || targetIdx >= len(q.args) {
		return false
	}
	expected := q.args[targetIdx].(string)
	switch op {
	case "=":
		return actual == expected
	case "!=":
		return actual != expected
	case "LIKE":
		return strings.Contains(actual, expected)
	}
	return false
}

func (q *SessionQuery) compareActive(actual bool, op string) bool {
	targetIdx := -1

	for i, w := range q.where {
		parts := splitWhere(w)
		if len(parts) == 2 && parts[0] == "Active" && parts[1] == op {
			targetIdx = i
			break
		}
	}
	if targetIdx < 0 || targetIdx >= len(q.args) {
		return false
	}
	expected := q.args[targetIdx].(bool)
	switch op {
	case "=":
		return actual == expected
	case "!=":
		return actual != expected
	}
	return false
}

// mockSessionStore 实现 SessionStore 接口的内存版本，用于单元测试。
type mockSessionStore struct {
	mu   sync.RWMutex
	data map[int64]*Session
}

// NewMockSessionStore 创建 Mock Store 实例。
func NewMockSessionStore() *mockSessionStore {
	return &mockSessionStore{
		data: make(map[int64]*Session),
	}
}

// cloneSession 逐字段拷贝记录，bytes/slice 深拷贝保证数据隔离。
// 不整体复制 struct：protoimpl.MessageState 含锁，整体赋值会触发 vet copies lock。
func cloneSession(src *Session) *Session {
	if src == nil {
		return nil
	}
	dst := &Session{}
	dst.Id = src.Id
	dst.Token = src.Token
	dst.UserId = src.UserId
	dst.Active = src.Active
	return dst
}

// Create 创建记录。
func (m *mockSessionStore) Create(record *Session) error {
	if record == nil {
		return fmt.Errorf("sqlitex: cannot create nil Session")
	}
	m.mu.Lock()
	defer m.mu.Unlock()
	if _, exists := m.data[record.Id]; exists {
		return fmt.Errorf("sqlitex: Session with Id=%v already exists", record.Id)
	}
	// 深拷贝避免外部修改
	m.data[record.Id] = cloneSession(record)
	return nil
}

// Update 更新记录。
func (m *mockSessionStore) Update(record *Session) error {
	if record == nil {
		return fmt.Errorf("sqlitex: cannot update nil Session")
	}
	m.mu.Lock()
	defer m.mu.Unlock()
	if _, exists := m.data[record.Id]; !exists {
		return fmt.Errorf("sqlitex: Session with Id=%v not found", record.Id)
	}
	m.data[record.Id] = cloneSession(record)
	return nil
}

// Delete 删除记录。
func (m *mockSessionStore) Delete(Id int64) error {
	m.mu.Lock()
	defer m.mu.Unlock()
	delete(m.data, Id)
	return nil
}

// Get 按主键查询。
func (m *mockSessionStore) Get(Id int64) (*Session, error) {
	m.mu.RLock()
	defer m.mu.RUnlock()
	record, exists := m.data[Id]
	if !exists {
		return nil, nil
	}
	return cloneSession(record), nil
}

// PurgeExpired 内存 Mock 不模拟 TTL 语义，恒返回 0。
// 接口兼容用，TTL 行为请使用真实 Store 验证。
func (m *mockSessionStore) PurgeExpired() (int, error) {
	return 0, nil
}
