// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v4.25.6
// source: ttl_user.proto

package ttluser

import (
	_ "github.com/mogumc/sqlitex/proto/sqlitex"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Session 演示 Phase 3 TTL 生命周期管理。
// token 字段声明 ttl = "1s"，表示该记录在写入 1 秒后过期。
// 读取时惰性删除（含索引行同步清理），Compaction 阶段物理回收。
type Session struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Token         string                 `protobuf:"bytes,2,opt,name=token,proto3" json:"token,omitempty"`
	UserId        string                 `protobuf:"bytes,3,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Active        bool                   `protobuf:"varint,4,opt,name=active,proto3" json:"active,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Session) Reset() {
	*x = Session{}
	mi := &file_ttl_user_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Session) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Session) ProtoMessage() {}

func (x *Session) ProtoReflect() protoreflect.Message {
	mi := &file_ttl_user_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Session.ProtoReflect.Descriptor instead.
func (*Session) Descriptor() ([]byte, []int) {
	return file_ttl_user_proto_rawDescGZIP(), []int{0}
}

func (x *Session) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Session) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *Session) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *Session) GetActive() bool {
	if x != nil {
		return x.Active
	}
	return false
}

var File_ttl_user_proto protoreflect.FileDescriptor

const file_ttl_user_proto_rawDesc = "" +
	"\n" +
	"\x0ettl_user.proto\x12\aexample\x1a\x15sqlitex/options.proto\"\x84\x01\n" +
	"\aSession\x12\x16\n" +
	"\x02id\x18\x01 \x01(\x03B\x06\x8a\xb5\x18\x02\x18\x01R\x02id\x12\x1e\n" +
	"\x05token\x18\x02 \x01(\tB\b\x8a\xb5\x18\x04\"\x021sR\x05token\x12\x1f\n" +
	"\auser_id\x18\x03 \x01(\tB\x06\x8a\xb5\x18\x02\b\x01R\x06userId\x12\x16\n" +
	"\x06active\x18\x04 \x01(\bR\x06active:\b\x82\xb5\x18\x04\n" +
	"\x02idB+Z)github.com/mogumc/sqlitex/example/ttluserb\x06proto3"

var (
	file_ttl_user_proto_rawDescOnce sync.Once
	file_ttl_user_proto_rawDescData []byte
)

func file_ttl_user_proto_rawDescGZIP() []byte {
	file_ttl_user_proto_rawDescOnce.Do(func() {
		file_ttl_user_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_ttl_user_proto_rawDesc), len(file_ttl_user_proto_rawDesc)))
	})
	return file_ttl_user_proto_rawDescData
}

var file_ttl_user_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_ttl_user_proto_goTypes = []any{
	(*Session)(nil), // 0: example.Session
}
var file_ttl_user_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_ttl_user_proto_init() }
func file_ttl_user_proto_init() {
	if File_ttl_user_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_ttl_user_proto_rawDesc), len(file_ttl_user_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_ttl_user_proto_goTypes,
		DependencyIndexes: file_ttl_user_proto_depIdxs,
		MessageInfos:      file_ttl_user_proto_msgTypes,
	}.Build()
	File_ttl_user_proto = out.File
	file_ttl_user_proto_goTypes = nil
	file_ttl_user_proto_depIdxs = nil
}
