package codegen

import (
	"fmt"
	"strings"

	"google.golang.org/protobuf/types/pluginpb"
)

// GenerateResponse 是协调器，读取 CodeGeneratorRequest，生成 CodeGeneratorResponse。
// 所有 Message 表合并输出到单个 *_sqlitex.go 文件，公共辅助代码（zstd/splitWhere）只生成一次。
func GenerateResponse(req *pluginpb.CodeGeneratorRequest) *pluginpb.CodeGeneratorResponse {
	resp := &pluginpb.CodeGeneratorResponse{}

	// 解析参数
	params := parseParams(req.GetParameter())

	// 构建 IR
	tables, err := BuildIR(req.ProtoFile)
	if err != nil {
		errStr := fmt.Sprintf("build IR: %v", err)
		resp.Error = &errStr
		return resp
	}

	if len(tables) == 0 {
		// 无 sqlitex table，不生成任何文件
		return resp
	}

	// 确定输出的包名
	pkgName := params["package"]
	if pkgName == "" {
		// 默认从第一个表的 GoPackage 取值
		pkgName = tables[0].GoPackage
	}
	if pkgName == "" {
		pkgName = "generated"
	}

	// 统一所有表的 GoPackage
	for _, t := range tables {
		t.GoPackage = pkgName
	}

	// 收集所有表的代码段
	var sections []string
	for _, table := range tables {
		// 序列化代码
		sections = append(sections, GenerateSerializer(table))
		// Store 接口 + 实现
		sections = append(sections, GenerateStore(table))
		// Fluent Query Builder
		queryCode, qerr := GenerateQuery(table)
		if qerr != nil {
			errStr := fmt.Sprintf("generate query for %s: %v", table.MessageName, qerr)
			resp.Error = &errStr
			return resp
		}
		sections = append(sections, queryCode)
		// Mock 实现
		sections = append(sections, GenerateMock(table))
	}

	// 合并所有表代码到单个文件，preamble 只注入一次
	merged := mergeAllSections(pkgName, sections)

	fileName := tables[0].MessageName + "_sqlitex.go"
	content := fmt.Sprintf(`// Code generated by protoc-gen-sqlitex. DO NOT EDIT.
// source: %s

%s
`, getSourceFiles(req, tables[0].MessageName), merged)

	resp.File = append(resp.File, &pluginpb.CodeGeneratorResponse_File{
		Name:    &fileName,
		Content: &content,
	})

	return resp
}

// mergeAllSections 合并所有表代码段，去重 import，并注入只生成一次的 preamble。
func mergeAllSections(pkgName string, sections []string) string {
	importSet := make(map[string]bool)
	var codeBodies []string

	for _, sec := range sections {
		imports, body := extractImports(sec)
		for _, imp := range imports {
			importSet[imp] = true
		}
		codeBodies = append(codeBodies, body)
	}

	// 注入 zstd 辅助 import（preamble 需要）
	importSet["zstd \"github.com/klauspost/compress/zstd\""] = true

	var buf strings.Builder
	buf.WriteString("package " + pkgName + "\n\n")

	if len(importSet) > 1 {
		buf.WriteString("import (\n")
		for imp := range importSet {
			buf.WriteString("\t" + imp + "\n")
		}
		buf.WriteString(")\n\n")
	}

	// 注入公共 preamble（zstd 辅助 + splitWhere）
	buf.WriteString(GeneratePreamble())
	buf.WriteString("\n")

	for _, body := range codeBodies {
		buf.WriteString(body)
		buf.WriteString("\n")
	}

	return buf.String()
}

// parseParams 解析逗号分隔的键值对参数。
func parseParams(paramStr string) map[string]string {
	result := make(map[string]string)
	if paramStr == "" {
		return result
	}
	for _, kv := range strings.Split(paramStr, ",") {
		parts := strings.SplitN(strings.TrimSpace(kv), "=", 2)
		if len(parts) == 2 {
			result[parts[0]] = parts[1]
		} else if len(parts) == 1 && parts[0] != "" {
			result[parts[0]] = "true"
		}
	}
	return result
}

// getSourceFiles 查找与某个 Message 关联的源文件名。
func getSourceFiles(req *pluginpb.CodeGeneratorRequest, msgName string) string {
	for _, f := range req.ProtoFile {
		for _, m := range f.MessageType {
			if m.GetName() == msgName {
				return f.GetName()
			}
		}
	}
	return "unknown.proto"
}

// extractImports 从 Go 源码中提取 import 块和后续代码体。
func extractImports(code string) ([]string, string) {
	lines := linesOf(code)
	var imports []string

	i := 0
	// 跳过 package 行和之间的空行
	for i < len(lines) {
		line := strings.TrimSpace(lines[i])
		if line == "" || strings.HasPrefix(line, "package ") {
			i++
			continue
		}
		break
	}

	// 提取 import 块
	if i < len(lines) && strings.TrimSpace(lines[i]) == "import (" {
		i++ // 跳过 "import ("
		for i < len(lines) {
			line := strings.TrimSpace(lines[i])
			if line == ")" {
				i++
				break
			}
			// 保留完整的 import 行（含别名和引号），仅去掉首尾空格
			impLine := strings.TrimSpace(line)
			if impLine != "" {
				imports = append(imports, impLine)
			}
			i++
		}
	}

	body := strings.Join(lines[i:], "\n")
	return imports, body
}

func linesOf(s string) []string {
	raw := strings.Split(s, "\n")
	var result []string
	for _, line := range raw {
		result = append(result, line)
	}
	return result
}
