package codegen

import (
	"fmt"
	"strings"

	"google.golang.org/protobuf/types/pluginpb"
)

// GenerateResponse 是协调器，读取 CodeGeneratorRequest，生成 CodeGeneratorResponse。
func GenerateResponse(req *pluginpb.CodeGeneratorRequest) *pluginpb.CodeGeneratorResponse {
	resp := &pluginpb.CodeGeneratorResponse{}

	// 解析参数
	params := parseParams(req.GetParameter())

	// 构建 IR
	tables, err := BuildIR(req.ProtoFile)
	if err != nil {
		errStr := fmt.Sprintf("build IR: %v", err)
		resp.Error = &errStr
		return resp
	}

	if len(tables) == 0 {
		// 无 sqlitex table，不生成任何文件
		return resp
	}

	// 确定输出的包名
	pkgName := params["package"]
	if pkgName == "" {
		// 默认从第一个表的 GoPackage 取值
		pkgName = tables[0].GoPackage
	}
	if pkgName == "" {
		pkgName = "generated"
	}

	// 统一所有表的 GoPackage
	for _, t := range tables {
		t.GoPackage = pkgName
	}

	// 为每个表生成代码
	for _, table := range tables {
		// 序列化代码
		serializerCode := GenerateSerializer(table)

		// Store 接口 + 实现
		storeCode := GenerateStore(table)

		// Fluent Query Builder
		queryCode, _ := GenerateQuery(table)

		// Mock 实现
		mockCode := GenerateMock(table)

		// 合并输出到一个文件：统一 package + import
		sections := []string{serializerCode, storeCode, queryCode, mockCode}
		merged := mergeCodeSections(pkgName, sections)

		fileName := table.MessageName + "_sqlitex.go"
		content := fmt.Sprintf(`// Code generated by protoc-gen-sqlitex. DO NOT EDIT.
// source: %s

%s
`, getSourceFiles(req, table.MessageName), merged)

		resp.File = append(resp.File, &pluginpb.CodeGeneratorResponse_File{
			Name:    &fileName,
			Content: &content,
		})
	}

	return resp
}

// parseParams 解析逗号分隔的键值对参数。
func parseParams(paramStr string) map[string]string {
	result := make(map[string]string)
	if paramStr == "" {
		return result
	}
	for _, kv := range strings.Split(paramStr, ",") {
		parts := strings.SplitN(strings.TrimSpace(kv), "=", 2)
		if len(parts) == 2 {
			result[parts[0]] = parts[1]
		} else if len(parts) == 1 && parts[0] != "" {
			result[parts[0]] = "true"
		}
	}
	return result
}

// getSourceFiles 查找与某个 Message 关联的源文件名。
func getSourceFiles(req *pluginpb.CodeGeneratorRequest, msgName string) string {
	for _, f := range req.ProtoFile {
		for _, m := range f.MessageType {
			if m.GetName() == msgName {
				return f.GetName()
			}
		}
	}
	return "unknown.proto"
}

// mergeCodeSections 合并多个代码段，去除重复的 package 和 import 声明。
func mergeCodeSections(pkgName string, sections []string) string {
	// 收集所有 unique imports
	importSet := make(map[string]bool)
	var codeBodies []string

	for _, sec := range sections {
		imports, body := extractImports(sec)
		for _, imp := range imports {
			importSet[imp] = true
		}
		codeBodies = append(codeBodies, body)
	}

	// 构建输出
	var buf strings.Builder
	buf.WriteString("package " + pkgName + "\n\n")

	if len(importSet) > 0 {
		buf.WriteString("import (\n")
		for imp := range importSet {
			buf.WriteString("\t\"" + imp + "\"\n")
		}
		buf.WriteString(")\n\n")
	}

	// 特殊处理：在包声明后添加 var _ 占位符（来自 serializer）
	var vars string
	for _, line := range codeBodies {
		// 收集所有 var _ = xxx 行
		for _, l := range linesOf(line) {
			if len(l) > 5 && l[:6] == "var _ =" {
				if !strings.Contains(vars, l) {
					vars += l + "\n"
				}
			}
		}
	}

	if vars != "" {
		buf.WriteString(vars + "\n")
	}

	for _, body := range codeBodies {
		// 移除 var _ 行（已在顶部统一声明）
		body = stripVarUnderbars(body)
		buf.WriteString(body)
		buf.WriteString("\n")
	}

	return buf.String()
}

// extractImports 从 Go 源码中提取 import 块和后续代码体。
func extractImports(code string) ([]string, string) {
	lines := linesOf(code)
	var imports []string

	i := 0
	// 跳过 package 行和之间的空行
	for i < len(lines) {
		line := strings.TrimSpace(lines[i])
		if line == "" || strings.HasPrefix(line, "package ") {
			i++
			continue
		}
		break
	}

	// 提取 import 块
	if i < len(lines) && strings.TrimSpace(lines[i]) == "import (" {
		i++ // 跳过 "import ("
		for i < len(lines) {
			line := strings.TrimSpace(lines[i])
			if line == ")" {
				i++
				break
			}
			// 移除引号
			line = strings.Trim(line, "\"\t ")
			if line != "" {
				imports = append(imports, line)
			}
			i++
		}
	}

	body := strings.Join(lines[i:], "\n")
	return imports, body
}

func linesOf(s string) []string {
	raw := strings.Split(s, "\n")
	var result []string
	for _, line := range raw {
		result = append(result, line)
	}
	return result
}

func stripVarUnderbars(s string) string {
	lines := linesOf(s)
	var result []string
	for _, line := range lines {
		if len(line) > 6 && line[:6] == "var _ =" {
			continue
		}
		result = append(result, line)
	}
	return strings.Join(result, "\n")
}
