// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v4.25.6
// source: sqlitex/options.proto

package sqlitexpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	descriptorpb "google.golang.org/protobuf/types/descriptorpb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// IndexOption 标记在字段上，声明该字段需要二级索引。
type IndexOption int32

const (
	// 不创建索引（默认）。
	IndexOption_INDEX_NONE IndexOption = 0
	// 普通索引，允许重复值。
	IndexOption_INDEX_NORMAL IndexOption = 1
	// 唯一索引，值必须唯一。
	IndexOption_INDEX_UNIQUE IndexOption = 2
)

// Enum value maps for IndexOption.
var (
	IndexOption_name = map[int32]string{
		0: "INDEX_NONE",
		1: "INDEX_NORMAL",
		2: "INDEX_UNIQUE",
	}
	IndexOption_value = map[string]int32{
		"INDEX_NONE":   0,
		"INDEX_NORMAL": 1,
		"INDEX_UNIQUE": 2,
	}
)

func (x IndexOption) Enum() *IndexOption {
	p := new(IndexOption)
	*p = x
	return p
}

func (x IndexOption) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (IndexOption) Descriptor() protoreflect.EnumDescriptor {
	return file_sqlitex_options_proto_enumTypes[0].Descriptor()
}

func (IndexOption) Type() protoreflect.EnumType {
	return &file_sqlitex_options_proto_enumTypes[0]
}

func (x IndexOption) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use IndexOption.Descriptor instead.
func (IndexOption) EnumDescriptor() ([]byte, []int) {
	return file_sqlitex_options_proto_rawDescGZIP(), []int{0}
}

// TableOption 标记在 Message 上，声明该 Message 对应一张表。
type TableOption struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 主键字段名（必填）。该字段必须是 int64/uint64/string 类型。
	PrimaryKey string `protobuf:"bytes,1,opt,name=primary_key,json=primaryKey,proto3" json:"primary_key,omitempty"`
	// 全局压缩开关。启用后对超过阈值的变长字段自动压缩。
	Compress bool `protobuf:"varint,2,opt,name=compress,proto3" json:"compress,omitempty"`
	// 压缩阈值（字节），仅当 compress=true 时生效。
	// 变长字段（string/bytes）超过此值时触发压缩，默认 256。
	CompressThreshold int32 `protobuf:"varint,3,opt,name=compress_threshold,json=compressThreshold,proto3" json:"compress_threshold,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *TableOption) Reset() {
	*x = TableOption{}
	mi := &file_sqlitex_options_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TableOption) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TableOption) ProtoMessage() {}

func (x *TableOption) ProtoReflect() protoreflect.Message {
	mi := &file_sqlitex_options_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TableOption.ProtoReflect.Descriptor instead.
func (*TableOption) Descriptor() ([]byte, []int) {
	return file_sqlitex_options_proto_rawDescGZIP(), []int{0}
}

func (x *TableOption) GetPrimaryKey() string {
	if x != nil {
		return x.PrimaryKey
	}
	return ""
}

func (x *TableOption) GetCompress() bool {
	if x != nil {
		return x.Compress
	}
	return false
}

func (x *TableOption) GetCompressThreshold() int32 {
	if x != nil {
		return x.CompressThreshold
	}
	return 0
}

// FieldOption 标记在字段上，控制字段级别的存储行为。
type FieldOption struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 是否为该字段创建索引。
	Index IndexOption `protobuf:"varint,1,opt,name=index,proto3,enum=sqlitex.IndexOption" json:"index,omitempty"`
	// 是否压缩该字段（覆盖表级 compress 设置）。
	// 仅对 string/bytes 类型有效。
	Compress bool `protobuf:"varint,2,opt,name=compress,proto3" json:"compress,omitempty"`
	// 是否作为主键字段（配合 TableOption.primary_key 使用）。
	PrimaryKey bool `protobuf:"varint,3,opt,name=primary_key,json=primaryKey,proto3" json:"primary_key,omitempty"`
	// TTL 过期时间字符串，如 "30d"、"24h"。
	// 过期数据在读取时惰性删除。
	Ttl           string `protobuf:"bytes,4,opt,name=ttl,proto3" json:"ttl,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FieldOption) Reset() {
	*x = FieldOption{}
	mi := &file_sqlitex_options_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FieldOption) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FieldOption) ProtoMessage() {}

func (x *FieldOption) ProtoReflect() protoreflect.Message {
	mi := &file_sqlitex_options_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FieldOption.ProtoReflect.Descriptor instead.
func (*FieldOption) Descriptor() ([]byte, []int) {
	return file_sqlitex_options_proto_rawDescGZIP(), []int{1}
}

func (x *FieldOption) GetIndex() IndexOption {
	if x != nil {
		return x.Index
	}
	return IndexOption_INDEX_NONE
}

func (x *FieldOption) GetCompress() bool {
	if x != nil {
		return x.Compress
	}
	return false
}

func (x *FieldOption) GetPrimaryKey() bool {
	if x != nil {
		return x.PrimaryKey
	}
	return false
}

func (x *FieldOption) GetTtl() string {
	if x != nil {
		return x.Ttl
	}
	return ""
}

var file_sqlitex_options_proto_extTypes = []protoimpl.ExtensionInfo{
	{
		ExtendedType:  (*descriptorpb.MessageOptions)(nil),
		ExtensionType: (*TableOption)(nil),
		Field:         50000,
		Name:          "sqlitex.table",
		Tag:           "bytes,50000,opt,name=table",
		Filename:      "sqlitex/options.proto",
	},
	{
		ExtendedType:  (*descriptorpb.FieldOptions)(nil),
		ExtensionType: (*FieldOption)(nil),
		Field:         50001,
		Name:          "sqlitex.field",
		Tag:           "bytes,50001,opt,name=field",
		Filename:      "sqlitex/options.proto",
	},
}

// Extension fields to descriptorpb.MessageOptions.
var (
	// optional sqlitex.TableOption table = 50000;
	E_Table = &file_sqlitex_options_proto_extTypes[0]
)

// Extension fields to descriptorpb.FieldOptions.
var (
	// optional sqlitex.FieldOption field = 50001;
	E_Field = &file_sqlitex_options_proto_extTypes[1]
)

var File_sqlitex_options_proto protoreflect.FileDescriptor

const file_sqlitex_options_proto_rawDesc = "" +
	"\n" +
	"\x15sqlitex/options.proto\x12\asqlitex\x1a google/protobuf/descriptor.proto\"y\n" +
	"\vTableOption\x12\x1f\n" +
	"\vprimary_key\x18\x01 \x01(\tR\n" +
	"primaryKey\x12\x1a\n" +
	"\bcompress\x18\x02 \x01(\bR\bcompress\x12-\n" +
	"\x12compress_threshold\x18\x03 \x01(\x05R\x11compressThreshold\"\x88\x01\n" +
	"\vFieldOption\x12*\n" +
	"\x05index\x18\x01 \x01(\x0e2\x14.sqlitex.IndexOptionR\x05index\x12\x1a\n" +
	"\bcompress\x18\x02 \x01(\bR\bcompress\x12\x1f\n" +
	"\vprimary_key\x18\x03 \x01(\bR\n" +
	"primaryKey\x12\x10\n" +
	"\x03ttl\x18\x04 \x01(\tR\x03ttl*A\n" +
	"\vIndexOption\x12\x0e\n" +
	"\n" +
	"INDEX_NONE\x10\x00\x12\x10\n" +
	"\fINDEX_NORMAL\x10\x01\x12\x10\n" +
	"\fINDEX_UNIQUE\x10\x02:P\n" +
	"\x05table\x12\x1f.google.protobuf.MessageOptions\x18І\x03 \x01(\v2\x14.sqlitex.TableOptionR\x05table\x88\x01\x01:N\n" +
	"\x05field\x12\x1d.google.protobuf.FieldOptions\x18ц\x03 \x01(\v2\x14.sqlitex.FieldOptionR\x05field\x88\x01\x01B3Z1github.com/mogumc/sqlitex/proto/sqlitex;sqlitexpbb\x06proto3"

var (
	file_sqlitex_options_proto_rawDescOnce sync.Once
	file_sqlitex_options_proto_rawDescData []byte
)

func file_sqlitex_options_proto_rawDescGZIP() []byte {
	file_sqlitex_options_proto_rawDescOnce.Do(func() {
		file_sqlitex_options_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_sqlitex_options_proto_rawDesc), len(file_sqlitex_options_proto_rawDesc)))
	})
	return file_sqlitex_options_proto_rawDescData
}

var file_sqlitex_options_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_sqlitex_options_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_sqlitex_options_proto_goTypes = []any{
	(IndexOption)(0),                    // 0: sqlitex.IndexOption
	(*TableOption)(nil),                 // 1: sqlitex.TableOption
	(*FieldOption)(nil),                 // 2: sqlitex.FieldOption
	(*descriptorpb.MessageOptions)(nil), // 3: google.protobuf.MessageOptions
	(*descriptorpb.FieldOptions)(nil),   // 4: google.protobuf.FieldOptions
}
var file_sqlitex_options_proto_depIdxs = []int32{
	0, // 0: sqlitex.FieldOption.index:type_name -> sqlitex.IndexOption
	3, // 1: sqlitex.table:extendee -> google.protobuf.MessageOptions
	4, // 2: sqlitex.field:extendee -> google.protobuf.FieldOptions
	1, // 3: sqlitex.table:type_name -> sqlitex.TableOption
	2, // 4: sqlitex.field:type_name -> sqlitex.FieldOption
	5, // [5:5] is the sub-list for method output_type
	5, // [5:5] is the sub-list for method input_type
	3, // [3:5] is the sub-list for extension type_name
	1, // [1:3] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_sqlitex_options_proto_init() }
func file_sqlitex_options_proto_init() {
	if File_sqlitex_options_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_sqlitex_options_proto_rawDesc), len(file_sqlitex_options_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   2,
			NumExtensions: 2,
			NumServices:   0,
		},
		GoTypes:           file_sqlitex_options_proto_goTypes,
		DependencyIndexes: file_sqlitex_options_proto_depIdxs,
		EnumInfos:         file_sqlitex_options_proto_enumTypes,
		MessageInfos:      file_sqlitex_options_proto_msgTypes,
		ExtensionInfos:    file_sqlitex_options_proto_extTypes,
	}.Build()
	File_sqlitex_options_proto = out.File
	file_sqlitex_options_proto_goTypes = nil
	file_sqlitex_options_proto_depIdxs = nil
}
